### ISSUE TITLE
Please update the Doc link

### ISSUE THREAD

**Issue by pkochar263** [sjoerdk/clockifyclient#2]
* Clockify API Python client version: Latest
* Python version:3.7
* Operating System: windows 10

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
Trying to understad the working of python API
```
 Doc is not avaiable on the following lnk :- 
https://clockify-api-client.readthedocs.io/
```

**Comment by sjoerdk** [comment]
That link was left over boilerplate from cookiecutter. There currently are no separate docs pages. For examples, please see [the examples folder](https://github.com/sjoerdk/clockifyclient/tree/master/examples)

I've removed the docs link for now (06636f4c437e61905734ed5245b1a12d21c66d08) . If anyone want to write docs in /docs I'd be happy to push them.
