### ISSUE TITLE
Contributing to the repository - documentation and new features

### ISSUE THREAD

**Issue by lukasab** [sjoerdk/clockifyclient#6]
### Description

Hey @sjoerdk, I came across this repository while thinking about creating a wrapper for the clockify API. Instead of creating another one I wanted to check if I could contribute to your existing rep. Are there any open issues or new features I could help with?  I could also help with documentation (creating a [Read the Docs](https://readthedocs.org/) for the project).

**Comment by sjoerdk** [comment]
Hi @lukasab nice to hear. One open issue right now is simply is updating requirements_dev.txt to make it secure and the pyup shield nice and green again. You can just take all the latest versions from https://pyup.io/repos/github/sjoerdk/clockifyclient/ If you could do that that would be great.

The lib currently only implements a small subset of all of the clockify API functions. This is enough for my own usage at the moment. If you are missing any features I'd be happy to discuss or review a PR.

Read the docs documentation would definitely be an improvement. Any contributions welcome there

**Comment by lukasab** [comment]
@sjoerdk awesome I'll work on that first then! If you don't mind I will create an issue for the requirements and read the docs documentation.
